pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

include ':rxandroidble', ':dagger-compiler-shadow', ':dagger-library-shadow'
include ':sample', ':sample-kotlin', ':mockrxandroidble'

rootProject.name = 'rxandroidble-parent'