name: "Gradle Actions"
on: [push, pull_request]

jobs:
  gradle_validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6
      - name: "Validate"
        uses: gradle/actions/wrapper-validation@v6
  gradle_tasks:
    name: "Gradle Tasks"
    runs-on: ubuntu-latest
    needs: gradle_validation
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6
      - name: "Set up Android JDK environment"
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v6
      - name: "Run Checkstyle"
        run: ./gradlew checkstyle
      - name: "Run Unit Tests — RxAndroidBle"
        run: ./gradlew :rxandroidble:testDebugUnitTest
      - name: "Run Unit Tests — MockClient"
        run: ./gradlew :mockrxandroidble:testDebugUnitTest
      - name: "Run Unit Tests — Sample Kotlin"
        run: ./gradlew :sample-kotlin:testDebugUnitTest
