# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish to Sonatype

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and Publish
        env:
          CENTRAL_PORTAL_TOKEN_KEY: ${{ secrets.CENTRAL_PORTAL_TOKEN_KEY }}
          CENTRAL_PORTAL_TOKEN_SECRET: ${{ secrets.CENTRAL_PORTAL_TOKEN_SECRET }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          PUBLISHING: true
        run: ./gradlew :rxandroidble:publishToSonatype :mockrxandroidble:publishToSonatype :dagger-library-shadow:publishToSonatype closeAndReleaseSonatypeStagingRepository
